
-----------------------------------------------------------------
LOADING EXPERIMENTS AND APPLYING OVERRIDES.... (faas_runner.py)
-----------------------------------------------------------------


Overrides: {}

Loaded function: {'function': 'FunctionTest1', 'platform': 'AWS Lambda', 'source': '../java_template', 'endpoint': 'https://wlg6bdz050.execute-api.us-west-2.amazonaws.com/hello_dev/', 'sourceFile': 'functions/cpuIntensiveFunctionCallConfig.json'}

---Loaded function list: [{'function': 'FunctionTest1', 'platform': 'AWS Lambda', 'source': '../java_template', 'endpoint': 'https://wlg6bdz050.execute-api.us-west-2.amazonaws.com/hello_dev/', 'sourceFile': 'functions/cpuIntensiveFunctionCallConfig.json'}]
NOTE: parentPayload missing in experiment file! Using default option of {}
NOTE: payloadFolder missing in experiment file! Using default option of 
NOTE: shufflePayloads missing in experiment file! Using default option of False
NOTE: passPayloads missing in experiment file! Using default option of False
NOTE: transitions missing in experiment file! Using default option of {}

Loaded experiment: {'callWithCLI': True, 'callAsync': False, 'memorySettings': [], 'payloads': [{'name': 100000}], 'runs': 50, 'threads': 50, 'iterations': 1, 'sleepTime': 5, 'randomSeed': 42, 'outputGroups': ['cpuType', 'containerID', 'vmID', 'newcontainer', 'zAll'], 'outputRawOfGroup': [], 'showAsList': [], 'showAsSum': ['newcontainer'], 'ignoreFromAll': ['zAll', 'lang', 'version', 'linuxVersion', 'platform', 'hostname'], 'ignoreFromGroups': ['1_run_id', '2_thread_id', 'cpuModel', 'cpuIdle', 'cpuIowait', 'cpuIrq', 'cpuKrn', 'cpuNice', 'cpuSoftIrq', 'cpuUsr'], 'ignoreByGroup': {'containerID': ['containerID'], 'cpuType': ['cpuType'], 'vmID': ['vmID']}, 'invalidators': {}, 'removeDuplicateContainers': False, 'overlapFilter': 'functionName', 'openCSV': True, 'combineSheets': False, 'warmupBuffer': 0, 'sourceFile': 'experiments/cpuIntensiveTaskExperiment.json', 'experimentName': 'cpuIntensiveTaskExperiment', 'parentPayload': {}, 'payloadFolder': '', 'shufflePayloads': False, 'passPayloads': False, 'transitions': {}}

---Loaded experiment list: [{'callWithCLI': True, 'callAsync': False, 'memorySettings': [], 'payloads': [{'name': 100000}], 'runs': 50, 'threads': 50, 'iterations': 1, 'sleepTime': 5, 'randomSeed': 42, 'outputGroups': ['cpuType', 'containerID', 'vmID', 'newcontainer', 'zAll'], 'outputRawOfGroup': [], 'showAsList': [], 'showAsSum': ['newcontainer'], 'ignoreFromAll': ['zAll', 'lang', 'version', 'linuxVersion', 'platform', 'hostname'], 'ignoreFromGroups': ['1_run_id', '2_thread_id', 'cpuModel', 'cpuIdle', 'cpuIowait', 'cpuIrq', 'cpuKrn', 'cpuNice', 'cpuSoftIrq', 'cpuUsr'], 'ignoreByGroup': {'containerID': ['containerID'], 'cpuType': ['cpuType'], 'vmID': ['vmID']}, 'invalidators': {}, 'removeDuplicateContainers': False, 'overlapFilter': 'functionName', 'openCSV': True, 'combineSheets': False, 'warmupBuffer': 0, 'sourceFile': 'experiments/cpuIntensiveTaskExperiment.json', 'experimentName': 'cpuIntensiveTaskExperiment', 'parentPayload': {}, 'payloadFolder': '', 'shufflePayloads': False, 'passPayloads': False, 'transitions': {}}]

-----------------------------------------------------------------
PREPARING PAYLOADS... (experiment_orchestrator.py)
-----------------------------------------------------------------

Not loading payloads from folder. Either folder does not exist of payloadFolder is undefined.
Skipping setting memory value.
Sleeping after setting memory value...
Running test 0: 

-----------------------------------------------------------------
CREATING AND RUNNING THREADS FOR EXPERIMENT (experiment_caller.py)
-----------------------------------------------------------------

Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
Call Payload: {'name': 100000}
STDOUT: 

STDERR: 
Run 36.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 4.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 3.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 39.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 14.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 2.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 15.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 19.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 0.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 12.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 24.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 29.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 677, in emit
    return self._events.emit(event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 328, in service_model
    return self._get_service_model()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 347, in _get_service_model
    self._service_model = self.session.get_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 492, in get_service_model
    service_description = self.get_service_data(service_name, api_version)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 512, in get_service_data
    service_data = self.get_component('data_loader').load_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 387, in load_service_model
    self._extras_processor.process(model, extras_data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 455, in process
    for extras in extra_models:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 398, in _find_extras
    yield self.load_data(full_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 424, in load_data
    raise DataNotFoundError(data_path=name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/exceptions.py", line 40, in __init__
    msg = self.fmt.format(**kwargs)
KeyboardInterrupt

Run 40.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 128, in _build_command_table
    command_table = self._build_builtin_commands(self.session)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 137, in _build_builtin_commands
    services = session.get_available_services()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 527, in get_available_services
    return self.get_component('data_loader')\
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 279, in list_available_services
    api_versions = os.listdir(full_dirname)
KeyboardInterrupt

Run 49.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 17.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 35.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 677, in emit
    return self._events.emit(event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 328, in service_model
    return self._get_service_model()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 347, in _get_service_model
    self._service_model = self.session.get_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 492, in get_service_model
    service_description = self.get_service_data(service_name, api_version)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 512, in get_service_data
    service_data = self.get_component('data_loader').load_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 374, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 279, in list_available_services
    api_versions = os.listdir(full_dirname)
KeyboardInterrupt

Run 34.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 677, in emit
    return self._events.emit(event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 328, in service_model
    return self._get_service_model()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 347, in _get_service_model
    self._service_model = self.session.get_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 492, in get_service_model
    service_description = self.get_service_data(service_name, api_version)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 512, in get_service_data
    service_data = self.get_component('data_loader').load_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 383, in load_service_model
    model = self.load_data(full_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 420, in load_data
    found = self.file_loader.load_file(possible_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 175, in load_file
    return json.loads(payload, object_pairs_hook=OrderedDict)
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
KeyboardInterrupt

Run 43.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 16.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 28.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 26.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 33.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 18.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 25.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 13.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 22.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 206, in main
    parsed_args, remaining = parser.parse_known_args(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/argparser.py", line 101, in parse_known_args
    parsed, remaining = super(CLIArgParser, self).parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2000, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1970, in consume_positionals
    arg_counts = match_partial(positionals, selected_pattern)
  File "/usr/lib/python3.8/argparse.py", line 2126, in _match_arguments_partial
    match = _re.match(pattern, arg_strings_pattern)
  File "/usr/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 498, in _parse
    subpatternappend = subpattern.append
KeyboardInterrupt

Run 44.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 1.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 8.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 21.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 23.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 677, in emit
    return self._events.emit(event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 328, in service_model
    return self._get_service_model()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 347, in _get_service_model
    self._service_model = self.session.get_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 492, in get_service_model
    service_description = self.get_service_data(service_name, api_version)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 512, in get_service_data
    service_data = self.get_component('data_loader').load_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 374, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 268, in list_available_services
    for possible_path in self._potential_locations():
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 431, in _potential_locations
    if os.path.isdir(path):
KeyboardInterrupt
STDOUT: 

STDERR: 
Run 45.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 

Run 48.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 9.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 10.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 5.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 37.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 38.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 677, in emit
    return self._events.emit(event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 328, in service_model
    return self._get_service_model()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 347, in _get_service_model
    self._service_model = self.session.get_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 492, in get_service_model
    service_description = self.get_service_data(service_name, api_version)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 512, in get_service_data
    service_data = self.get_component('data_loader').load_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 374, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 284, in list_available_services
    if self.file_loader.exists(full_load_path):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 154, in exists
    return os.path.isfile(file_path + '.json')
  File "/usr/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
KeyboardInterrupt

Run 46.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 677, in emit
    return self._events.emit(event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 328, in service_model
    return self._get_service_model()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 347, in _get_service_model
    self._service_model = self.session.get_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 492, in get_service_model
    service_description = self.get_service_data(service_name, api_version)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 512, in get_service_data
    service_data = self.get_component('data_loader').load_service_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 374, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/loaders.py", line 279, in list_available_services
    api_versions = os.listdir(full_dirname)
KeyboardInterrupt

Run 47.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 7.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 11.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 20.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 31.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 30.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 6.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 41.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 27.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 677, in emit
    return self._events.emit(event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/awscli/customizations/preview.py", line 73, in mark_as_preview
    session.get_component('event_emitter').register_last(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 378, in register_last
    aliased_event_name = self._alias_event_name(event_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py", line 416, in _alias_event_name
    logger.debug("Changing event name from %s to %s" % (
  File "/usr/lib/python3.8/logging/__init__.py", line 1421, in debug
    if self.isEnabledFor(DEBUG):
  File "/usr/lib/python3.8/logging/__init__.py", line 1685, in isEnabledFor
    return self._cache[level]
KeyboardInterrupt

Run 42.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
STDOUT: 

STDERR: 
Run 32.0 Failed with exception: unexpected EOF while parsing (<unknown>, line 0).
Request Response: 
